version: "3.0"
services:
  dwn-server:
    image: ghcr.io/tbd54566975/dwn-server:main
    ports:
      - 3100:3100
    volumes:
      - ./.dwn-data/:/dwn-server/data
    environment:
      - DS_PORT=3100
      - DS_MAX_RECORD_DATA_SIZE=100gb
    platform: linux/amd64
